webtalk_init -webtalk_dir D:/Especialidad sistemas embebidos UBA/Circuitos_logicos_pro/Clase_1/pwm/Sintesis/pwm.sim/sim_1/behav/xsim/xsim.dir/pwm_mmc_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Apr 24 01:51:58 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "82c60076-4774-4bbf-a45d-c860b272c364" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b3153187119642a3b9a1f9d9a6d5cc41" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "142" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "7.22_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15292_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2572754890 -regid "" -xml D:/Especialidad sistemas embebidos UBA/Circuitos_logicos_pro/Clase_1/pwm/Sintesis/pwm.sim/sim_1/behav/xsim/xsim.dir/pwm_mmc_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Especialidad sistemas embebidos UBA/Circuitos_logicos_pro/Clase_1/pwm/Sintesis/pwm.sim/sim_1/behav/xsim/xsim.dir/pwm_mmc_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Especialidad sistemas embebidos UBA/Circuitos_logicos_pro/Clase_1/pwm/Sintesis/pwm.sim/sim_1/behav/xsim/xsim.dir/pwm_mmc_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
